### ISSUE TITLE
Update nuget package

### ISSUE THREAD

**Issue by scattered-code** [FaithLV/SharpPwned.NET#10]
Hi,
Could you please push the latest version to nuget?

Thanks

**Comment by valters-tomsons** [comment]
Hi, I have not used the API in a while, including this library. People have been contributing fixes and updates, so assume it works in some capacity. If it does not, let me know and I'll see what I can do.

I have updated the repository, pushed `2.0.1` to NuGet and marked old versions as deprecated.
