### ISSUE TITLE
API Requests being blocked

### ISSUE THREAD

**Issue by ghost** [FaithLV/SharpPwned.NET#5]
I used the code example you provided in the readme, and my application just freezes, no data output into textbox, why?

**Comment by valters-tomsons** [comment]
There's no textbox in the example. Could you show exactly what you are doing?

**Comment by ghost** [comment]
My code is
`{
    var client = new HaveIBeenPwnedRestClient();
    var response = client.GetAccountBreaches(TextBox4.Text).Result;

    foreach (Breach x in response)
    {
        TextBox5.Text = (x.Domain) + Constants.vbCrLf;
    }
}
`
The code doesn't do anything, I even tried using "Try" but there is no exception.

**Comment by valters-tomsons** [comment]
Looks like there's an issue with the API. 

-removed-

I've sent a message to the API maintainer.

**Comment by ghost** [comment]
Yep, first link works but second says that I'm blocked

**Comment by martinst1** [comment]
@FaithLV did you find a solution? I also have a client for the HIBP api and it also doesn't work.

**Comment by ghost** [comment]
Api is fixed, so client works now @martinst1

**Comment by ghost** [comment]
Now requests are not being blocked but the code still doesn't work

**Comment by valters-tomsons** [comment]
I cannot test it myself ATM, could you try a manual request with UserAgent "SharpPwned.NET"? 

You could also try specifing a different UserAgent by passing it to the constructor of the client library.
