### ISSUE TITLE
V3

### ISSUE THREAD

**Issue by bobbyK12345** [FaithLV/SharpPwned.NET#7]
How can I update this to support V3 of the API - I need to wrap an API key into the GET request.

Thanks!

**Comment by ShvetsovZE** [comment]
@bobbyK12345 
1. Fork out the repo to you to your account.
2. Make the changes 
3. Send a pull request to the original master branch
Cheers!

**Comment by hoppushoppard** [comment]
I did a PR for API version 3
https://github.com/FaithLV/SharpPwned.NET/pull/9
